name: Daily Heat Index Push

on:
  schedule:
    - cron: '0 1,3,5,7 * * *'  # 台灣時間 9、11、13、15 點
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run main script
      env:
        LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        GROUP_ID: ${{ secrets.GROUP_ID }}
      run: python main.py
